# Numpy Exercises

# Import Numpy as np

# Create an array of 15 zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# Create an array of 15 ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Create an array of 15 sevens

array([7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7.])

# create an array of the integers from 5 to 75

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
       56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72,
       73, 74, 75])

# create an array of all the even integers from 2 to 80

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78])

# Create a 4X4 matrix with values ranging from 0 to 15

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

# Create a 4X4 identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Use Numpy to generate a random numbre between 0 and 1

array([0.97314248])

# Use Numpy to generate an array of 35 random numbers sampled from a standard normal destributionr

array([ 1.54197742, -0.2625101 ,  0.47866635, -0.22182426,  0.51863518,
        0.12504325,  0.7673915 , -0.63569546, -0.541619  , -0.71199597,
        1.28604544, -0.74417406, -0.09228423,  2.08171417, -0.67376337,
        1.48272312, -0.11134147,  0.10077741,  0.42277033, -0.23177279,
        1.63928453,  0.03511514, -1.09877654, -0.17752928, -0.92724946,
       -0.19788706, -0.65746416,  0.14260769, -0.08635449, -0.9710303 ,
       -0.70900888, -1.77089007, -0.17560794,  0.26589484, -0.81483274])

# create the following matrix

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

# Create an array of 30 linearly spaced points between 0 and 1

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

# Numpy Indexing and Selection

In [24]:
matx = np.arange(1,50).reshape(7,7)
matx

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

array([[23, 24, 25, 26, 27, 28],
       [30, 31, 32, 33, 34, 35],
       [37, 38, 39, 40, 41, 42],
       [44, 45, 46, 47, 48, 49]])

40

array([[ 2],
       [ 9],
       [16],
       [23],
       [30]])

array([43, 44, 45, 46, 47, 48, 49])

array([43, 44, 45, 46, 47, 48, 49])

array([[29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

# Now Do The Followng

Get The Sum of All The Values In matx:

1225

Get The Standard deviation of the values in matx:

14.142135623730951

Get The sum of all the columns in matx:

array([154, 161, 168, 175, 182, 189, 196])