In [2]:
import numpy as np
array = np.arange(10)
squared_array = array ** 2
print(squared_array)

[ 0  1  4  9 16 25 36 49 64 81]


In [1]:
import numpy as np
a = np.arange(start=0, stop=6, step=1)
a2 = a[np.newaxis, :]
a2.shape
(1, 6)

(1, 6)

In [13]:
# Creating array object 
arr = np.array( [[ 1, 2, 3], 
                 [ 4, 2, 5]] ) 

In [11]:
# Printing type of arr object 
print("Array is of type: ", type(arr)) 

Array is of type:  <class 'numpy.ndarray'>


In [10]:
# Printing array dimensions (axes) 
print("No. of dimensions: ", arr.ndim) 

No. of dimensions:  2


In [8]:
# Printing shape of array 
print("Shape of array: ", arr.shape) 

Shape of array:  (2, 3)


In [7]:
# Printing size (total number of elements) of array 
print("Size of array: ", arr.size) 

Size of array:  6


In [6]:

# Printing type of elements in array 
print("Array stores elements of type: ", arr.dtype) 

Array stores elements of type:  int32


# NumPy Array Creation
There are various ways of Numpy array creation in Python. They are as follows:

1. You can create an array from a regular Python list or tuple using the array() function. 
The type of the resulting array is deduced from the type of the elements in the sequences. Let’s see this implementation:

In [14]:
# Creating array from list with type float 
a = np.array([[1, 2, 4], [5, 8, 7]], dtype = 'float') 
print ("Array created using passed list:\n", a) 
  


Array created using passed list:
 [[1. 2. 4.]
 [5. 8. 7.]]


In [15]:
# Creating array from tuple 
b = np.array((1 , 3, 2)) 
print ("\nArray created using passed tuple:\n", b)


Array created using passed tuple:
 [1 3 2]


2. Often, the element is of an array is originally unknown, but its size is known. Hence, NumPy offers several functions to create arrays with initial placeholder content. These minimize the necessity of growing arrays, an expensive operation. For example: np.zeros, np.ones, np.full, np.empty, etc.

To create sequences of numbers, NumPy provides a function analogous to the range that returns arrays instead of lists.

In [18]:


# Creating a 3X4 array with all zeros 
c = np.zeros((3, 4)) 
print ("An array initialized with all zeros:\n", c) 
  


An array initialized with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [17]:
# Create a constant value array of complex type 
d = np.full((3, 3), 6, dtype = 'complex') 
print ("An array initialized with all 6s." 
            "Array type is complex:\n", d) 


An array initialized with all 6s.Array type is complex:
 [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]


In [19]:
  
# Create an array with random values 
e = np.random.random((2, 2)) 
print ("A random array:\n", e)

A random array:
 [[0.20955801 0.95695253]
 [0.60752987 0.72579549]]


3. arange: This function returns evenly spaced values within a given interval. Step size is specified.

In [20]:


# Create a sequence of integers  
# from 0 to 30 with steps of 5 
f = np.arange(0, 30, 5) 
print ("A sequential array with steps of 5:\n", f)

A sequential array with steps of 5:
 [ 0  5 10 15 20 25]


4. linspace: It returns evenly spaced values within a given interval.

In [21]:


# Create a sequence of 10 values in range 0 to 5 
g = np.linspace(0, 5, 10) 
print ("A sequential array with 10 values between"
                                 "0 and 5:\n",)
print(g)

A sequential array with 10 values between0 and 5:
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
